---
language: go
sudo: false
go:
- 1.4.3
- 1.5.1
- tip
env:
- TESTARCH=amd64 RACE=-race
- TESTARCH=386
install: true
before_script:
- bin/fetch-configlet
- bin/configlet .
script:
- GOARCH=$TESTARCH go test -cpu 2 $RACE --tags example  ./...
matrix:
  exclude:
  - go: 1.4.3
    env: TESTARCH=386
  allow_failures:
  - go: tip
